### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Release v1.0.0 for the Marketplace

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-profanity-filter/issues/16

### CODE REVIEW

**Comment by hanzei** [comment]
cc @aaronrothschild

**Review by iomodo — APPROVED** [review]

**Comment by aaronrothschild** [comment]
Please do not merge this yet.  The Readme file needs to be updated - it has zero information about the plugin.  

Can we also change the text here to "Censor out profanity from user messages in real-time based on a list of words"

image

I couldn't test latest version, but last version....it didn't show the list of bad words on the config screen.  Was that fixed in this version?

**Comment by hanzei** [comment]
> Please do not merge this yet. The Readme file needs to be updated - it has zero information about the plugin.

Opened https://github.com/mattermost/mattermost-plugin-profanity-filter/issues/18. 

> Can we also change the text here to "Censor out profanity from user messages in real-time based on a list of words"


Sure, updated via 80bbcb7
 
> I couldn't test latest version, but last version....it didn't show the list of bad words on the config screen. Was that fixed in this version?


Yes, that setting will get added in this release.
Screenshot from 2020-09-01 20-40-55

**Comment by DHaussermann** [comment]
@hanzei after testing the profanity filter, It has some usability issues and problems with words being targeted that contain spaces. 
Because of these issues, the plugin could filter out unexpected words or reject posts that contain words for no obvious reason and depending on config, block the post without feedback.  

We should really consider holding off making this available in the marketplace until at least https://github.com/mattermost/mattermost-plugin-profanity-filter/issues/21 and https://github.com/mattermost/mattermost-plugin-profanity-filter/issues/20 have been addressed. 

Ideally https://github.com/mattermost/mattermost-plugin-profanity-filter/issues/22 would be fixed as well as the filter can be circumvented is an easy way that is naturally discoverable. But, this is a less serious issue as it will not result in posts being unexpectedly blocked.

cc @aaronrothschild

**Comment by hanzei** [comment]
@aaronrothschild @DHaussermann This release should be ready. Could you please review?

**Review by aaronrothschild — APPROVED** [review]
LGTM! (I can't remove labels on this repo)

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- 3 issues mentioned above have now been resolved
- Briefly regression tested. No issues found.
- Version number correctly listed as 1.0.0

LGTM!

**Pull request merged**
